const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CARD_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    DECREASE_QTY: 'DECREASE_QTY',
    INCREASE_QTY: 'INCREASE_QTY',
    CLEAR_CART: 'CLEAR_CART'
}

export default CartActionTypes